### ISSUE TITLE
Add ability to track updates

### ISSUE THREAD

**Issue by tyleroconnell** [yaelwrites/Big-Ass-Data-Broker-Opt-Out-List#14]
Thank you @yaelwrites for compiling this list, I've found it incredibly helpful!

I was wondering if you would be open to me creating a pull request to integrate [GitHub Action](https://github.com/features/actions) into this repository, to create a [release](https://github.com/yaelwrites/Big-Ass-Data-Broker-Opt-Out-List/releases) for each merge to the master branch.

This functionality would enable anyone interested in this repository to setup a custom Watch setting (pictured below) to receive notifications whenever new data brokers are added to the list, making it easy to stay up-to-date with additions.
<img width="318" alt="image" src="https://user-images.githubusercontent.com/9032279/128035645-48be080b-9628-497e-a0c8-64785737a06c.png">

**Comment by yaelwrites** [comment]
Sure, that would be great!
