### ISSUE TITLE
TruthFinder & Instant CheckMate Use New Opt-Out URLs

### ISSUE THREAD

**Issue by DP3rS** [yaelwrites/Big-Ass-Data-Broker-Opt-Out-List#16]
The TruthFinder opt-out URL currently linked no longer successfully sends the requestor an email. Although it gives confirmation that an email has been sent, it is never received. TruthFinder has actually updated their opt-out to a new url which successfully sends an opt-out email: https://www.truthfinder.com/opt-out/v2

**Comment by DP3rS** [comment]
Turns out this also applies to Instant CheckMate as well. https://www.instantcheckmate.com/opt-out/v2

**Comment by yaelwrites** [comment]
Thanks! Looks like https://www.truthfinder.com/opt-out/v2/submit/ and https://www.instantcheckmate.com/opt-out/v2/submit/ might be best, so I'll switch to those!
