### ISSUE TITLE
Credit Freeze: Chex Systems 

### ISSUE THREAD

**Issue by danielcberman** [yaelwrites/Big-Ass-Data-Broker-Opt-Out-List#23]
Chex Systems, 1 (800) 428-9623. [https://www.chexsystems.com/security-freeze/place-freeze](https://www.chexsystems.com/security-freeze/place-freeze)
 
Chex Systems, Inc. (ChexSystems) is a nationwide specialty consumer reporting agency under the Fair Credit Reporting Act (FCRA). ChexSystems' clients regularly contribute information on closed checking and savings accounts. ChexSystems provides services to financial institutions and other types of companies that have a permissible purpose under the FCRA. ChexSystems' services primarily assist clients in assessing the risk of opening new accounts.

**Comment by yaelwrites** [comment]
Thank you. Are you suggesting doing this instead of Experian, et. al.? What are the benefits?

**Comment by danielcberman** [comment]
Not instead of, in addition to Experian, et. al. What a Chex System is supposed to be used for is to verify that you aren't opening and/or closing checking accounts one after another. For example if you are being added as a check signer for an organization, that organization might have a legitimate interest in knowing how you handle a checking account. If that's not happening in your life though why leave that data pathway open?

**Comment by yaelwrites** [comment]
Thank you; adding this now.
