### ISSUE TITLE
US carrier CallerID data brokers

### ISSUE THREAD

**Issue by joecool1029** [yaelwrites/Big-Ass-Data-Broker-Opt-Out-List#25]
There are 3 majors that work directly with the carriers. They slurp up data from wherever and attempt to attach a name to your phone numbers. It is often wrong. The opt-outs are on each page I link below. This is entirely separate from the other CallerID name brokers like OpenCNAM (acquired by Neustar, acquired by Transunion) which do not market directly to carriers. 

First Orion (used at least by T-Mobile, while they turned around data request in a day, they've yet to opt me out after 2 weeks)): https://privacy.firstorion.com/
Hiya: https://hiyahelp.zendesk.com/hc/en-us/requests/new (used at least by AT&T, say there's a problem with this number and there will be a selection to request that information be deleted).
TNS/Cequint (formerly used by Sprint/Tmo, possibly used by Verizon call filter?) : https://tnsi.com/privacy-policy/ opt-out methods listed here.

**Comment by yaelwrites** [comment]
Thank you. Are people entering your name to try to get a number, or the other way around?

**Comment by joecool1029** [comment]
They can enter a number and it spits back a name.

However, these brokers integrate in automatically with the carriers too so if your plan has caller id name feature (to show names for numbers not in your address book) these brokers are where the name provided comes from.

**Comment by yaelwrites** [comment]
So I am hesitant to include this because both First Orion and TNSI require information to tell you whether it has your data—I usually advise people to check to see if the company has their data before opting out from it. I’m also not sure what the security risk here is—people need your name to find out your phone number. 

Definitely open to discussing further, though!

**Comment by joecool1029** [comment]
The risk is that they hold a name tied to your number. Many people do not want this association.

In my case it's just an incorrect association so I get scammers and marketers that scan numbers looking for names and then call me looking for my mother's name, when she's never had an association with my number. Also, it is super annoying that I have a name that isn't mine show up on many caller ID's when I call people who don't have my number yet. 

Also, First Orion still has not honored my deletion request. I would invite any Californians reading this to place requests their own opt outs and file CCPA complaints when they inevitably don't comply.

**Comment by yaelwrites** [comment]
I think I am going to close this for now but am happy to revisit if there's ever a way to see whether the companies hold your information before providing them with information.
