### ISSUE TITLE
☠ Cyber Background Checks ☠

### ISSUE THREAD

**Issue by Scrut1ny** [yaelwrites/Big-Ass-Data-Broker-Opt-Out-List#35]
I noticed that Cyber Background Checks wasn't listed surprisingly, this website in my opinion is the highest priority to opt out of. You can search for Name, Address, Phone, and Email. Searches are 100% FREE and instant. The amount of info you can pull from someone is insane. Just have to add that the website is very simple and nice to use, works perfectly fine and theres no annoyances.

- Website [https://www.cyberbackgroundchecks.com/](https://www.cyberbackgroundchecks.com/)
- Opt out Request [https://www.cyberbackgroundchecks.com/removal](https://www.cyberbackgroundchecks.com/removal)

![image](https://github.com/yaelwrites/Big-Ass-Data-Broker-Opt-Out-List/assets/53458032/719e4bb5-dce4-4fb0-9211-f5432cdbfe98)

**Comment by yaelwrites** [comment]
Thanks, will add!
