### ISSUE TITLE
LocatePeople is unreachable

### ISSUE THREAD

**Issue by raphmim** [yaelwrites/Big-Ass-Data-Broker-Opt-Out-List#41]
I'm not if the company is out of business or changed domain, but [LocatePeople](https://github.com/yaelwrites/Big-Ass-Data-Broker-Opt-Out-List?tab=readme-ov-file#locatepeople) is unreachable. If they don't operate anymore, perhaps remove them from the list?

**Comment by yaelwrites** [comment]
Yes, I will remove this, thank you!
