### ISSUE TITLE
better optout for True People Search

### ISSUE THREAD

**Issue by sr10952** [yaelwrites/Big-Ass-Data-Broker-Opt-Out-List#43]
TL;DR

TruePeopleSearch uses Endato API and should be opted out from here
https://endato.com/privacy-policy/opt-out/

---
TruePeopleSearch.com has a "try our api for free" which redirects to https://endato.com/sign-up/tps/ endato has an opted out button listed above. 
I had my info showing on truepeoplesearch and submitted the opted out to endato and the results from true people search were gone pretty instantly (I DID provide my ssn. not sure if it worked otherwise)

**Comment by yaelwrites** [comment]
Thanks! Did you actually try the TruePeopleSearch opt-out first?

**Comment by sr10952** [comment]
No

**Comment by yaelwrites** [comment]
Thanks.

**Comment by yaelwrites** [comment]
(I would want to make sure people could see if Endato had their info before trying to opt out and possibly inadvertently giving them info.)

**Comment by sr10952** [comment]
So, my data was on true people search, and moments after opting out via
Entando, the true people search resulted in the data not being found.

**Comment by yaelwrites** [comment]
I understand. But I want to make sure that people can find their data on Entando (or that there's a clear link between the two sites) so they're not inadvertently sharing data with Entando that it does not already have. I also want to make sure that this works better than opting out on true people search itself.
