### ISSUE TITLE
California's data broker registry

### ISSUE THREAD

**Issue by sahal** [yaelwrites/Big-Ass-Data-Broker-Opt-Out-List#53]
I was reading an article by Brian Krebs yesterday and in the comments someone mentioned that California now requires data brokers to be registered with the state.  Each broker (that operates in that state) must register their opt-out link.  As of 2024, it looks like there are 501 registered data brokers in California alone.  There might be some data brokers that chose not to operate in California, I guess 🤷🏾.

* News article: https://krebsonsecurity.com/2024/08/nationalpublicdata-com-hack-exposes-a-nations-data/
* 2021-23 Registry Information: https://oag.ca.gov/data-brokers
* From 2024 onward data brokers are required to register with a different agency: https://cppa.ca.gov/data_brokers/

The 2024 list includes the following column headers:

1. Business name
2. Doing Business As (DBA), if applicable [optional] 
3. Business primary website
4. Business primary contact email address
5. Business primary phone number [optional]
6. Business primary street address
7. Business city
8. Business state abbreviation
9. Business zipcode
10. Business country
11. If the primary business address does not comport to the format for `#6-10`, please type the address in the box below: 
12. Does the business collect the personal information of minors? 
13. Does the business collect consumers' precise geolocation? 
14. Does the business collect consumers' reproductive health care data? 
15. Paste a link to a page on the business's website that contains details on how consumers may exercise their privacy rights by doing all of the following: 
  - Deleting personal information 
  - Correcting ...

Not sure how or if you want to incorporate this information into your opt out list.

**Comment by yaelwrites** [comment]
For this list I like to include information that works even in states that don't have a privacy law, like mine. Also the Delete Act won't fully roll out until I think 2026 (with some starting in 2025).

**Comment by sahal** [comment]
I see.

I thought since you've included CA specific links in your list in the past, you might want to use this as a resource too.  At the moment it looks like MyLife's opt-out URL on your list has 'ccpa' on it.  You also mention that non-California residents have been able to remove their information using that link.

I don't see a harm in mentioning that such a data-broker list exists -- even if its only applicable for California residents. Before I found your list, I didn't know that anyone was keeping a list like this.  Why not link to other resources that provide similar and sometimes more robust opt-out information?

**Comment by yaelwrites** [comment]
I think I've mentioned that I only include opt-outs that work for all states, not just California. But feel free to fork the repo and create a California-only list if you'd like!
